// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleAPI.Models;

namespace VehicleAPI.Migrations
{
    [DbContext(typeof(VehicleDBContext))]
    [Migration("20210628031223_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VehicleAPI.Models.VehicleDetail", b =>
                {
                    b.Property<string>("VIN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("InspectionDate")
                        .HasColumnType("datetime");

                    b.Property<string>("InspectionLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("InspectionNotes")
                        .HasColumnType("ntext");

                    b.Property<bool>("InspectionStatus")
                        .HasColumnType("bit");

                    b.Property<string>("InspectorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VehicleMaker")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VehicleModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("VIN");

                    b.ToTable("VehicleDetails");
                });

            modelBuilder.Entity("VehicleAPI.Models.VehicleMaker", b =>
                {
                    b.Property<string>("Maker_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Maker_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Maker_ID");

                    b.ToTable("VehicleMakers");
                });
#pragma warning restore 612, 618
        }
    }
}
